### ISSUE TITLE
Error launching "minecraft-pi-reborn-client"

### ISSUE THREAD

**Issue by PitchBlackNights** [MCPI-Revival/gMCPIL#12]
When I try to launch the mcpi reborn, it won't do anything. So i opened gMCPIL using terminal and it says this when i launch gMCPIL. 
```
(gmcpil:11242): Json-WARNING **: 20:58:59.438: Failed to deserialize "hud" property of type "(null)" for an object of type "GMCPILConfig"
(gmcpil:11242): Json-WARNING **: 20:58:59.438: Failed to deserialize "username" property of type "(null)" for an object of type "GMCPILConfig"
```

And when i try to launch the game...

 ```
[INFO]: Configuring Game...
[INFO]: Starting Game...
/opt/minecraft-pi-reborn-client/minecraft-pi: /usr/lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /opt/minecraft-pi-reborn-client/lib/libpng12.so.0)
```

I have zero idea how to fix this. I just know that i am missing an essential linux library file.

**Comment by nobody5050** [comment]
What OS, and Version are you on

**Comment by PitchBlackNights** [comment]
OS: Raspbian GNU/Linux 10 (buster)
Version: 10

found using "cat /etc/os-release

**Comment by nobody5050** [comment]
Can you try installing jMcpil?

**Comment by PitchBlackNights** [comment]
wont install, says:
```
./scripts/package.sh: 22: ./scripts/package.sh: pandoc: not found
```
when i try to install using "./scripts/package.sh

**Comment by PitchBlackNights** [comment]
i have openJDK 11
./scripts/package.sh also installed Gradle 6.4.1

**Comment by mobilegmYT** [comment]
> wont install, says:
> 
> ```
> ./scripts/package.sh: 22: ./scripts/package.sh: pandoc: not found
> ```
> 
> when i try to install using "./scripts/package.sh

Install it using the deb in releases

**Comment by mobilegmYT** [comment]
> And when i try to launch the game...
> 
> ```
> [INFO]: Configuring Game...
> [INFO]: Starting Game...
> /opt/minecraft-pi-reborn-client/minecraft-pi: /usr/lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /opt/minecraft-pi-reborn-client/lib/libpng12.so.0)
> ```
> 
> I have zero idea how to fix this. I just know that i am missing an essential linux library file.

Use https://cdn.discordapp.com/attachments/740287938453045401/889716959002898502/minecraft-pi-reborn-client_2.2.4_armhf.deb

**Comment by Alvarito050506** [comment]
Hi! This isn't a problem with gMCPIL, it's just you're trying to use a newer MCPI-Reborn version that only supports Bullseye or higher in a Buster system.

Actually, the first part of your report shows one of the old gMCPIL bugs that I haven't managed to fix yet, but I'm closing this since it isn't related to this particular issue.
