### ISSUE TITLE
Cant join multiplayer

### ISSUE THREAD

**Issue by lyneve64** [MCPI-Revival/gMCPIL#16]
I have been really enjoying Minecraft: Pi Edition recently. But i cannot connect to servers, unless they are LAN worlds.
I have 2 servers in the list when in the launcher, but MCPI doesnt see the servers.

I use the version: **Modded MCPE**
Servers in the launchers list: **thebrokenrail.com pbptanarchy.tk**

In game when i clicked "join game"
![In game when Join Game clicked](https://user-images.githubusercontent.com/54736898/150688002-3e699004-c3ab-4149-8d2d-c57a5b34bd4e.png)

main screen with the version
![Main Screen with game version](https://user-images.githubusercontent.com/54736898/150688004-2a8289b2-1c70-47b9-8878-7696919dc3e1.png)

server list when in launcher
![Server List](https://user-images.githubusercontent.com/54736898/150688005-eba28a57-bf79-4654-a5e2-bdd1650ea2ff.png)
`

**Comment by ArkQuark** [comment]
i too can join to the pi server this problem not in gMCPIL

**Comment by nobody5050** [comment]
@ArkQuark is right that this isn't a gMCIL problem but let's see if we can't help you anyhow. How did you install mcpi reborn?

**Comment by Bigjango13** [comment]
I don't think this is a MCPI problem at all, thebrokenrail.com is down and pbptanarchy.tk has a whitelist.

**Comment by nobody5050** [comment]
>  and pbptanarchy.tk has a whitelist.

nevermind then, it seems nooz's quest to stop stevepi has taken him to the dark side

**Comment by ArkQuark** [comment]
> @ArkQuark is right that this isn't a gMCIL problem but let's see if we can't help you anyhow. How did you install mcpi reborn?
this problem not in mcpi its problem to the server(im tried join from my phone)

**Comment by NoozAbooz** [comment]
> > and pbptanarchy.tk has a whitelist.
> 
> nevermind then, it seems nooz's quest to stop stevepi has taken him to the dark side

Most of the recent stevepi griefs were leha :(
