### ISSUE TITLE
Move FPS counter to top-right

### ISSUE THREAD

**Issue by mobilegmYT** [MCPI-Revival/gMCPIL#4]
I couldn't find the code that launches mcpi-reborn. Anyways if possible, use `GALLIUM_HUD=simple,.x750fps` when launching it so it's on the right side.

**Comment by Alvarito050506** [comment]
Hey! This is actually a MCPI-Reborn "issue"...

**Comment by mobilegmYT** [comment]
> Hey! This is actually a MCPI-Reborn "issue"...

Wdym?

**Comment by StealthHydra179** [comment]
Its not a problem caused by gMCPIL
